from tkinter import *

pro = Tk()
pro.geometry('500x500')
################################
b1  = Button(pro,text="circle",cursor="circle")
b1.pack()
b2  = Button(pro,text="plus",cursor="plus")
b2.pack()
b3  = Button(pro,text="mouse",cursor="mouse")
b3.pack()
b4  = Button(pro,text="target",cursor="target")
b4.pack()
b5  = Button(pro,text="cross",cursor="cross")
b5.pack()
b6  = Button(pro,text="clock",cursor="clock")
b6.pack()
b7  = Button(pro,text="heart",cursor="heart")
b7.pack()
b8  = Button(pro,text="spider",cursor="spider")
b8.pack()
b9  = Button(pro,text="sizing",cursor="sizing")
b9.pack()
b10  = Button(pro,text="trek",cursor="trek")
b10.pack()
lbl  = Label(pro,text="woooow",cursor="trek")
lbl.pack()
################################
pro.mainloop()